"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, BarChart3, Brain, CircleAlert, Code2, Lightbulb, Menu, Sparkles, X } from "lucide-react";
import { ChatInput } from "@/components/ChatInput";
import { Message } from "@/components/Message";
import { Sidebar } from "@/components/Sidebar";
import { ThemeToggle } from "@/components/ThemeToggle";
import type { ChatAttachment, ChatMessage, Conversation, Feedback } from "@/types/chat";
import type { AgentSettings } from "@/lib/agent/types";
import { createId } from "@/lib/id";
import { loadConversations, loadFeedback, saveConversations, saveFeedback } from "@/lib/storage";

const makeMessage = (role: ChatMessage["role"], content: string): ChatMessage => ({ id: createId(), role, content, createdAt: Date.now() });
const makeConversation = (): Conversation => ({ id: createId(), title: "New conversation", messages: [], updatedAt: Date.now() });
const defaultSettings: AgentSettings = { webSearch: true, fileAnalysis: true, voice: true, responseStyle: "balanced" };
const suggestions = [{ label: "Explain something", detail: "Get clear and simple explanations", prompt: "Explain this concept clearly", icon: Lightbulb, tone: "violet" }, { label: "Write code", detail: "Generate, debug, and explain code", prompt: "Help me write some code", icon: Code2, tone: "blue" }, { label: "Brainstorm ideas", detail: "Get creative ideas and perspectives", prompt: "Help me brainstorm ideas", icon: Brain, tone: "mint" }, { label: "Analyze a problem", detail: "Break down complex problems", prompt: "Help me analyze this problem", icon: BarChart3, tone: "gold" }];

export default function Chat() {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [activeId, setActiveId] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [focusSignal, setFocusSignal] = useState(0);
  const [showLatest, setShowLatest] = useState(false);
  const [settings, setSettings] = useState<AgentSettings>(defaultSettings);
  const messagesRef = useRef<HTMLElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => { const handle = window.setTimeout(() => { const stored = loadConversations(); const feedback = loadFeedback(); const initial = (stored.length ? stored : [makeConversation()]).map((conversation) => ({ ...conversation, messages: conversation.messages.map((message) => feedback[message.id] ? { ...message, feedback: feedback[message.id] } : message) })); setConversations(initial); setActiveId(initial[0].id); const savedSettings = localStorage.getItem("nexus-agent-settings"); if (savedSettings) { try { setSettings({ ...defaultSettings, ...JSON.parse(savedSettings) }); } catch { /* Keep defaults. */ } } }, 0); return () => window.clearTimeout(handle); }, []);
  useEffect(() => { if (conversations.length) saveConversations(conversations); }, [conversations]);
  useEffect(() => { localStorage.setItem("nexus-agent-settings", JSON.stringify(settings)); }, [settings]);
  const active = conversations.find((item) => item.id === activeId) ?? conversations[0];
  function replaceConversation(id: string, update: (item: Conversation) => Conversation) { setConversations((items) => items.map((item) => item.id === id ? update(item) : item)); }
  useEffect(() => { const handle = window.setTimeout(() => { if (!showLatest) bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, 0); return () => window.clearTimeout(handle); }, [active?.messages.length, loading, showLatest]);
  function newChat() { const next = makeConversation(); setConversations((items) => [next, ...items]); setActiveId(next.id); setError(""); setMobileOpen(false); setFocusSignal((value) => value + 1); }
  function deleteChat(id: string) { setConversations((items) => { const remaining = items.filter((item) => item.id !== id); const next = remaining.length ? remaining : [makeConversation()]; if (id === activeId) setActiveId(next[0].id); return next; }); }
  function renameChat(id: string, title: string) { replaceConversation(id, (item) => ({ ...item, title, updatedAt: Date.now() })); }
  function pinChat(id: string) { replaceConversation(id, (item) => ({ ...item, pinned: !item.pinned, updatedAt: Date.now() })); }
  function feedback(messageId: string, value: Feedback) { const stored = loadFeedback(); if (stored[messageId] === value) delete stored[messageId]; else stored[messageId] = value; saveFeedback(stored); if (active) replaceConversation(active.id, (item) => ({ ...item, messages: item.messages.map((message) => message.id === messageId ? { ...message, feedback: message.feedback === value ? undefined : value } : message) })); }
  async function requestResponse(conversationId: string, history: ChatMessage[], assistantId: string, attachments: ChatAttachment[] = []) { setLoading(true); setError(""); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: history, attachments, settings }) }); const data = await response.json().catch(() => null) as { message?: unknown; error?: string; details?: string } | null; if (!response.ok) throw new Error(data?.details ? `${data.error || "The AI service could not respond."} ${data.details}` : data?.error || "The AI service could not respond."); if (typeof data?.message !== "string" || !data.message.trim()) throw new Error("The AI service returned an empty response."); replaceConversation(conversationId, (item) => ({ ...item, messages: item.messages.map((message) => message.id === assistantId ? { ...message, content: data.message as string } : message), updatedAt: Date.now() })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Network error. Please try again."); replaceConversation(conversationId, (item) => ({ ...item, messages: item.messages.filter((message) => message.id !== assistantId) })); } finally { setLoading(false); } }
  async function sendMessage(content: string, attachments: ChatAttachment[] = []) { if (!active || loading) return; const userMessage = makeMessage("user", content); const assistant = makeMessage("assistant", ""); const history = [...active.messages, userMessage]; replaceConversation(active.id, (item) => ({ ...item, title: item.messages.length ? item.title : content.slice(0, 34), messages: [...history, assistant], updatedAt: Date.now() })); await requestResponse(active.id, history, assistant.id, attachments); }
  async function regenerate(messageIndex: number) { if (!active || loading) return; const target = active.messages[messageIndex]; if (!target || target.role !== "assistant") return; const history = active.messages.slice(0, messageIndex); const assistant = makeMessage("assistant", ""); replaceConversation(active.id, (item) => ({ ...item, messages: [...history, assistant], updatedAt: Date.now() })); await requestResponse(active.id, history, assistant.id); }
  async function editMessage(messageIndex: number, content: string) { if (!active || loading) return; const history = [...active.messages.slice(0, messageIndex), makeMessage("user", content)]; const assistant = makeMessage("assistant", ""); replaceConversation(active.id, (item) => ({ ...item, title: messageIndex === 0 ? content.slice(0, 34) : item.title, messages: [...history, assistant], updatedAt: Date.now() })); await requestResponse(active.id, history, assistant.id); }
  function handleScroll() { const element = messagesRef.current; if (!element) return; setShowLatest(element.scrollHeight - element.scrollTop - element.clientHeight > 180); }
  function scrollLatest() { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); setShowLatest(false); }
  if (!active) return null;
  return <div className="app-shell"><Sidebar conversations={conversations} activeId={active.id} mobileOpen={mobileOpen} settings={settings} onSettingsChange={setSettings} onNew={newChat} onSelect={setActiveId} onDelete={deleteChat} onRename={renameChat} onPin={pinChat} onClose={() => setMobileOpen(false)} /><main className="chat-main"><header className="chat-header"><button className="icon-button menu-button" aria-label="Open sidebar" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="header-copy"><p className="eyebrow">AI AGENT / GENERAL INTELLIGENCE</p><h1>{active.title}</h1></div><div className="header-actions"><div className="header-status"><span className="status-dot" /> Online</div><ThemeToggle /></div></header><section className="messages-area" ref={messagesRef} onScroll={handleScroll}><div className="messages-inner">{active.messages.length === 0 ? <div className="empty-state"><div className="welcome-brand"><div className="welcome-mark"><Sparkles size={22} /></div><div><strong>NEXUS</strong><span>Your Intelligent AI Agent</span></div></div><h2>What can I help <em>you</em> with?</h2><p className="welcome-copy">I can think, write, code, analyze, search, and help you with anything you need.<br />Just ask, and I&apos;ll handle the rest.</p><div className="suggestions">{suggestions.map(({ label, detail, prompt, icon: Icon, tone }) => <button className="suggestion-card" key={label} onClick={() => sendMessage(prompt)}><span className={`suggestion-icon ${tone}`}><Icon size={18} /></span><span className="suggestion-text"><strong>{label}</strong><small>{detail}</small></span><span className="suggestion-arrow"><ArrowUpRight size={15} /></span></button>)}</div></div> : active.messages.map((message, index) => <Message key={message.id} message={message} index={index} busy={loading} onRegenerate={() => regenerate(index)} onEdit={(content) => editMessage(index, content)} onFeedback={(value) => feedback(message.id, value)} />)}{loading && <div className="typing-row"><div className="avatar agent-avatar">N</div><div><div className="typing-label">NEXUS is thinking<span>...</span></div><div className="typing-indicator"><i /><i /><i /></div></div></div>}{error && <div className="error-banner"><CircleAlert size={16} /><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss error"><X size={15} /></button></div>}<div ref={bottomRef} /></div></section>{showLatest && <button className="latest-button" onClick={scrollLatest}>Scroll to latest</button>}<ChatInput disabled={loading} focusSignal={focusSignal} onSubmit={sendMessage} /></main></div>;
}